#!/bin/bash
LIVE_FILE='/usr/bin/live'
if [[ $# -ge 1 ]]; then
    LIVE_FILE='/usr/bin/'$1
fi
if [[ -e $LIVE_FILE ]]; then
    echo 'Warning: File '$LIVE_FILE' already exists!'
    exit
fi
echo '#!/bin/bash' > $LIVE_FILE
echo 'livestreamer $1 best' >> $LIVE_FILE
chmod a+x $LIVE_FILE
echo 'Created '$LIVE_FILE
