#!/bin/bash

# sudo ln -s `pwd`/live_file /usr/bin/mybin/live

LIVE_FILE_NAME='/usr/bin/live'
if [[ $# -ge 1 ]]; then
    LIVE_FILE_NAME='/usr/bin/'$1
fi

if [[ -e $LIVE_FILE_NAME ]]; then
    echo 'Warning: File '$LIVE_FILE_NAME' already exists!'
    echo 'No action taken'
    exit
fi

cp live_file $LIVE_FILE_NAME
chmod a+x $LIVE_FILE_NAME
echo 'Created '$LIVE_FILE_NAME
