#!/usr/bin/env python

import sys
import subprocess

argv = sys.argv
stream = ''
if len(sys.argv) > 1:
    stream = sys.argv[1]
else:
    clipboard = subprocess.check_output('xclip -selection clipboard -o', shell=True)
    print('Buffer contained the following address: {}'.format(clipboard))
    stream = clipboard

if len(sys.argv) <= 2 or (len(sys.argv) > 2 and sys.argv[2] != '--no-edit'):
    stream = stream.replace('?channel=', '')

print('Using following address: {}'.format(stream))
try:
    subprocess.call('livestreamer {} best'.format(stream), shell=True)
except KeyboardInterrupt:
    print('Stream ended')
